# BEGIN_KITTY_THEME
# Desert
# END_KITTY_THEME

shell zsh

font_family VictorMono Nerd Font
font_size 12.0

# Powerline symbols for starship
symbol_map U+E0A0-U+E0A3,U+E0C0-U+E0C7 PowerlineSymbols

# Nord
include current-theme.conf
window_border_width 1pt
active_border_color none
inactive_border_color #b48ead
inactive_text_alpha 0.8
draw_minimal_borders yes
window_padding_width 12

enabled_layouts tall,horizontal,fat,vertical
allow_remote_control yes
# END_KITTY_THEME

map ctrl+shift+t launch --type=tab --cwd=current
map ctrl+shift+enter launch --cwd=current
enable_audio_bell no

clipboard_control write-clipboard,read-clipboard
